package com.anoop.examples.controllers;

import com.anoop.examples.config.InjectIotoUser;
import com.anoop.examples.model.Alert;
import com.anoop.examples.model.IotoUser;
import com.anoop.examples.services.alerts.AlertService;
import io.swagger.annotations.ApiOperation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@Slf4j
@Controller
@RestController
@RequestMapping("v1/alerts")
public class AlertController {

  @Autowired
  private AlertService alertService;

  @Operation(summary = "Creates the alert and send to cloud")
  @ApiResponse(
          responseCode = "200",
          description = "Alert which is created created")
  @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE,
          produces = MediaType.APPLICATION_JSON_VALUE)
  public Alert send(@InjectIotoUser IotoUser user, @RequestBody Alert alert) {
    return alertService.create(alert, user);
  }

  @Operation(summary = "Returns a list of alerts generated by the device.")
  @ApiResponse(
          responseCode = "200",
          description = "List of alerts")
  @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
  public List<Alert> getAll(@InjectIotoUser IotoUser user) {
    return alertService.getByDeviceId(user.getUserName());
  }

  @Operation(summary = "Returns the alert for the id.")
  @ApiResponse(
          responseCode = "200",
          description = "Alert object")
  @Parameter(
          name = "id",
          in = ParameterIn.PATH,
          description = "the id of the alert")
  @GetMapping(value = {"/{id}"}, produces = MediaType.APPLICATION_JSON_VALUE)
  public Alert get(@PathVariable(value = "id") String id) {
    return alertService.get(id);
  }

  @ApiOperation(value = "Delete an alert", code = 204)
  @Parameter(
          name = "id",
          in = ParameterIn.PATH,
          description = "the id of the alert")
  @DeleteMapping("/{id}")
  @ResponseStatus(HttpStatus.OK)
  public ResponseEntity<?> delete(@InjectIotoUser IotoUser user,
                                  @PathVariable(value = "id") String id) {
    alertService.delete(id, user);
    return ResponseEntity.noContent().build();
  }
}
